# Generated by Django 5.2 on 2026-03-17 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='careerrecommendation',
            name='job_suggestions',
        ),
        migrations.RemoveField(
            model_name='careerrecommendation',
            name='post_graduation_options',
        ),
        migrations.AlterField(
            model_name='psychometrictest',
            name='category',
            field=models.CharField(choices=[('graduation', 'Graduation Stream')], max_length=20),
        ),
    ]
