# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_careerrecommendation_job_suggestions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='trait',
            field=models.CharField(choices=[('analytical', 'Analytical'), ('technical', 'Technical'), ('creative', 'Creative'), ('social', 'Social'), ('business', 'Business')], max_length=20, null=True, blank=True),
        ),
    ]
