# Generated by Django 5.2 on 2026-03-17 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_question_trait'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correct_answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='field',
            field=models.CharField(blank=True, choices=[('technical', 'Technical'), ('analytical', 'Analytical'), ('creative', 'Creative'), ('business', 'Business'), ('social', 'Social'), ('medical', 'Medical')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('single_choice', 'Single Choice'), ('multiple_choice', 'Multiple Choice'), ('scale', 'Scale 1-5'), ('yes_no', 'Yes/No'), ('knowledge', 'Knowledge Based')], max_length=20),
        ),
    ]
